TouraineTech/tourainetech.github.io

- README.md
- src/index.html
> feature(gMaps) : adding a google map with Polytech address

- img/calendar.svg
- img/logo_tnt.svg
- src/global.scss
- src/index.html
j'ai modifié le fichier scss + le html est-ce que c'est good ? :/
> modifications design

- .travis.yml
> configure travis to deploy on firebase

- package.json
- src/global.scss
- src/index.html
Permit to import svg inline in html :
```html
<div>
${require('!!svg-inline-loader!../img/1_design.svg')}
</div>
```
Second advantage : optimise ugly exported svg.
> some fixes and authorize inline svg import :

- src/global.scss
- src/index.html
> Gestion responsive

- README.md
- build/deployGhPages.js
- build/webpack.config.js
> added comments on build files

- src/agenda/agenda.json
Extracted links from twitter / speaker slack channel.
> after(): slide links

- src/agenda/agenda.json
- src/agenda/talkDescription.html.js
I created a new property tnt_video as I am not really fan of displaying the video of other conferences. 
To be discussed !
> feature(keynoteSlidesAndVideo) :

- package-lock.json
- src/global.scss
- src/index.html
- src/partials/footer.html
- src/partials/header.html
- src/partials/presentation.html
Temporary landing page for 2019 event.
Hacky but temporary so it does not matter (IMO)
⚠️ Need to move old site to 2018.touraine.tech  ⚠️
> chore(): 2019 landing page

- components/Register.vue
The ticket number is not visible anymore, this can be merged as soon as we want to open the ticketting
> feature(ticketing) : add helloAsso ticketing

- tools/backup_speakers_extract.js
Added a basic node script to craft mail content for backup speakers
> chore(): tooling 🛠

- api/team.json
- components/About.vue
- components/CFP.vue
- components/Footer.vue
- components/Header2022.vue
- components/Navbar2022.vue
- components/header/HeaderPhrase.vue
- components/header/buttons/RegisterSpeakerButton.vue
- layouts/default.vue
- nuxt.config.js
- package-lock.json
- package.json
- pages/index.vue
Basic landing page for TNT '22
> feat(landing2022): basic landing page for 22 edition

- components/Register.vue
> feat: sold out

- layouts/default.vue
- nuxt.config.js
- package-lock.json
- package.json
- plugins/smartbanner.client.js
Added smartbanner for Chapito/TNT app
> feat(smartbanner): ✨ add smartbanner for TNT app

- pages/speaker/_displayName.vue
- pages/sponsor/_name.vue
- pages/talk/_id.vue
Coucou :wave: 
Petit fix pour vos titres de pages, on a remarqué que c'était tjrs 2020 avec @yannbertrand.
> fix: update speaker, talk and sponsor pages title for TNT22

- components/About.vue
- nuxt.config.js
Disable smartbanner as the app is not ready for prime time yet
> fix(smartbanner): disable smartbanner

- README.md
- assets/configuration.js
- components/BeginnerSpeakers.vue
- components/Header2022.vue
- components/header/buttons/BeginnerSpeakerLink.vue
- components/header/buttons/RegisterAttendeeButton.vue
- components/header/buttons/RegisterSpeakerButton.vue
- pages/index.vue
> Add beginner speakers section

- components/Register.vue
Wave one soldout, tell the world wave two
> feat(soldOutWaveOne): Wave one sold out

- api/planning.json
Do Not Merge while waiting for acceptation by speaker
> feat(schedule) : move Audrey Dubois conference

- api/sponsors.json
> feat(sponsors) : add Polytech

- assets/img/logo.svg
> fix(tntLogo): restore old logo

- components/Schedule.vue
> feat(someCss) : allow to have 5 columns with the same width

- api/conferenceHall.json
This is my slides for my talk 😄
> 📝 Add my slides

- api/conferenceHall.json
> feat: add yannbertrand slides

- api/conferenceHall.json
Adding my slides for #TNT24 Talk: Comment devenir un parfait boyscout ?
> feat(slides): adding slides for Comment devenir un parfait boyscout ? talk

- components/BeginnerSpeakers.vue
- components/header/HeaderPhrase.vue
J'ai modifié un peu le contenu pour coller à ce qu'on avait dit sur le terme speaker :)
> feat: Rewording beginner speaker

- api/conferenceHall.json
- api/planning.json
- components/Schedule.vue
- tools/conferenceHallJsonExtractor.js
- tools/prePlanningBuilder.js
This was deleted by froufrou in 2019
I've added the level with an icone. I've also updated the time icone
> feat: add level in the planning

- components/RegieRoom.vue
- pages/regie/index.vue
> feat(captationRegie) : add a new page to remotely control all four OBS computer and monitor youtube streaming
